version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: appdist-postgres
    environment:
      POSTGRES_USER: appdist
      POSTGRES_PASSWORD: SET_DATABASE_PASSWORD_IN_ENV
      POSTGRES_DB: appdist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: appdist-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: SET_PRIVATE_VALUE_IN_ENV
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
